### ISSUE TITLE
Discover our EIP via CF DescribeStacks instead of Consul, so we can deploy jumphosts

### ISSUE THREAD

**Issue by gozer** [Nubisproject/nubis-jumphost#27]
successfully without Consul

**Comment by limed** [comment]
Command we can 

```bash
aws cloudformation describe-stacks --stack-name <stackname> --query 'Stacks[].Outputs[?OutputKey == `ElasticIP`].OutputValue' --output text
```

**Comment by gozer** [comment]
$> aws --region us-east-1 cloudformation describe-stacks --stack-name arn:aws:cloudformation:us-east-1:177680776199:stack/nubis-jumphost-stage/df883130-4da7-11e5-ab0b-50d5018a129a --query 'Stacks[].Outputs[?OutputKey == `ElasticIP`].OutputValue' --output text

**Comment by gozer** [comment]
@limed ++

**Comment by limed** [comment]
Will require fix of nubis-puppet-eip

**Comment by limed** [comment]
Also need to add an IAM line here https://github.com/Nubisproject/nubis-stacks/blob/master/eip.template#L60

Although with line https://github.com/Nubisproject/nubis-stacks/blob/master/eip.template#L63 we don't want that, we should probably create a separate policy for it

**Comment by gozer** [comment]
https://gist.github.com/gozer/9803bdb3f070850fce6f
